In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
y=np.array([[1,2,3],[4,5,6]])

In [5]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [7]:
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
list=[1,2,3,4]
sample_array=np.array(list)
print("List in python: ",list)
print("Array in python: ",sample_array)

List in python:  [1, 2, 3, 4]
Array in python:  [1 2 3 4]


In [10]:
type(list)

list

In [11]:
type(sample_array)

numpy.ndarray

In [12]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
sample_array=np.array([list1,list2,list3])
print("Numpy multidimensional array in python:\n",sample_array)

Numpy multidimensional array in python:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
x.ndim

1

In [15]:
y.ndim

2

In [16]:
z.ndim

3

In [19]:
b=np.array([1,2,3,4],ndim=5)

TypeError: array() got an unexpected keyword argument 'ndim'

In [20]:
b=np.array([1,2,3,4]).reshape(1,1,1,1,4)

In [21]:
b.ndim

5

In [22]:
b

array([[[[[1, 2, 3, 4]]]]])

In [23]:
arr=np.array([1,2,3,4])
print(arr[1])
print(arr[2])
print(arr[1]+arr[2])

2
3
5


In [24]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [25]:
y[0,2]

3

In [26]:
z[1,0,1]

6

In [27]:
z[1,1,1]

8

In [33]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.array([[1,2,3,7],[4,5,6,8]])
z=np.array([[[1,2,9],[3,4,10]],[[5,6,11],[7,8,12]]])

In [34]:
x[:2]

array([1, 2])

In [35]:
x[7:]

array([8, 9])

In [36]:
x[1:5:2]

array([2, 4])

In [37]:
x[::2]

array([1, 3, 5, 7, 9])

In [38]:
z.shape

(2, 2, 3)

In [39]:
z=np.array([[[1,2,9],[3,4,10]],[[5,6,11],[7,8,12]]])

In [46]:
z

array([[[ 1,  2,  9],
        [ 3,  4, 10]],

       [[ 5,  6, 11],
        [ 7,  8, 12]]])

In [41]:
z[1,0]

array([ 5,  6, 11])

In [42]:
z[1,0,2]

11

In [45]:
z[1,:,1]

array([6, 8])

In [48]:
z[1,:,2]

array([11, 12])

In [50]:
z[1,1,:]

array([ 7,  8, 12])

In [59]:
# z[0:2,0:2,2]
z[:,:,2]

array([[ 9, 10],
       [11, 12]])

In [66]:
z[:,:1,2]

array([[ 9],
       [11]])

In [65]:
z[:,0,2]

array([ 9, 11])

In [67]:
z.shape

(2, 2, 3)

In [68]:
x.dtype

dtype('int32')

In [70]:
arr=np.array([1.1,2.1,3.1])
print(arr.dtype)
new_arr=arr.astype('i')
print(new_arr.dtype)

float64
int32


In [73]:
#make a copy, change the original array, and display both arrays
arr=np.array([1,2,3,4])
a=arr.copy()
a[0]=5
print(arr)
print(a)

[1 2 3 4]
[5 2 3 4]


In [74]:
#make aview, change the original array, and display both arrays
arr=np.array([1,2,3,4])
a=arr.view()
a[0]=5
print(arr)
print(a)

[5 2 3 4]
[5 2 3 4]


In [88]:
arr=np.zeros((2,3,2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [93]:
arr=np.zeros((2,2),dtype=[('f','f'),('i','i')])
print(arr)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [96]:
c=np.ones(2,dtype=int)
c

array([1, 1])

In [97]:
c=np.ones((2,2),dtype=int)
c

array([[1, 1],
       [1, 1]])

In [98]:
c=np.ones((2,2))
c

array([[1., 1.],
       [1., 1.]])

In [99]:
c=np.ones([2,2],dtype=int)
c

array([[1, 1],
       [1, 1]])

In [100]:
c=np.ones([2,2])
c

array([[1., 1.],
       [1., 1.]])

In [104]:
#arange()
arr=np.arange(10).reshape(2,1,5)
print(arr)

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


In [112]:
arr=np.linspace(0,2,num=10)
print(arr)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [113]:
#flatten
arr=np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]


In [114]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


array([[[ 1,  2,  9],
        [ 3,  4, 10]],

       [[ 5,  6, 11],
        [ 7,  8, 12]]])

In [116]:
p=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [118]:
p.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [120]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [122]:
arr1=np.array([[1,2]])
arr2=np.array([[3,4],[5,6]])
arr=np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
p=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [ ]:
#aggregate functions

In [125]:
np.sum(p)

45

In [127]:
np.mean(p)

5.0

In [128]:
np.max(p)

9

In [129]:
np.min(p)

1

In [130]:
np.sqrt(p)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [131]:
#array modification

In [134]:
#insert no at desired num
arr=np.array([1,2,3,4])
new=np.insert(arr,2,100)
new

array([  1,   2, 100,   3,   4])

In [137]:
arr=np.array([[1,2],[3,4]])
new=np.insert(arr,1,[5,6],axis=0)
new

array([[1, 2],
       [5, 6],
       [3, 4]])

In [138]:
#append
arr=np.array([1,2,3,4])
new=np.append(arr,[100,200])
new

array([  1,   2,   3,   4, 100, 200])

In [139]:
#delete
arr=np.array([1,2,3,4])
new=np.delete(arr,0)
new

array([2, 3, 4])

In [143]:
arr=np.array([[1,2],[3,4]])
new=np.delete(arr,0)
new

array([2, 3, 4])

In [144]:
arr=np.array([[1,2],[3,4]])
new=np.delete(arr,0,axis=0)
new

array([[3, 4]])

In [147]:
#split
arr=np.array([1,2,3,4])
new=np.split(arr,2)
print(new)

[array([1, 2]), array([3, 4])]


In [148]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,2,2],[4,4,4]])
c=a+b
c

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [149]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[2,2],
            [2,4],
            [4,4]])
print(a.dot(b))

[[18 22]
 [42 52]]


Practice and Programs

In [151]:
#sum of elements of inividual row and individual column of matrix or order 3x3
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array is: ")
print(a)
for i in range(3):
    rs=0
    for j in range(3):
        rs=rs+a[i][j]
    print(f"Sum of row {i+1} is {rs}")
for j in range(3):
    cs=0
    for i in range(3):
        cs=cs+a[i][j]
    print(f"Sum of column {j+1} is {cs}")

Original array is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of row 1 is 6
Sum of row 2 is 15
Sum of row 3 is 24
Sum of column 1 is 12
Sum of column 2 is 15
Sum of column 3 is 18


In [154]:
#numpy methods are below explained with the help of examples in following
import numpy as np
ar1=np.array([2,3,5,3,1])
ar2=np.array([2,6,8,3,7])
print("Original arrays: ")
print(ar1)
print(ar2)
print("Comparison for >")
print(np.greater(ar1,ar2))
print("Comparison for >=")
print(np.greater_equal(ar1,ar2))
print("Comparison for <")
print(np.less(ar1,ar2))
print("Comparison for <=")
print(np.less_equal(ar1,ar2))
print("Comparison for =")
print(np.equal(ar1,ar2))
print("Comparison for !=")
print(np.not_equal(ar1,ar2))

Original arrays: 
[2 3 5 3 1]
[2 6 8 3 7]
Comparison for >
[False False False False False]
Comparison for >=
[ True False False  True False]
Comparison for <
[False  True  True False  True]
Comparison for <=
[ True  True  True  True  True]
Comparison for =
[ True False False  True False]
Comparison for !=
[False  True  True False  True]


In [2]:
#Matrix Inverse, Determinant & Rank
import numpy as np

A = np.array([[4, 7], [2, 6]])

print("Matrix:\n", A)
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))
print("Rank:", np.linalg.matrix_rank(A))


Matrix:
 [[4 7]
 [2 6]]
Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Rank: 2


In [3]:
#Eigenvalues and Eigenvectors
A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


In [4]:
#Broadcasting and Vectorization
arr = np.arange(9).reshape(3, 3)
print("Original:\n", arr)

# Broadcast scalar
print("Add 10 to all elements:\n", arr + 10)

# Broadcast row-wise
row = np.array([1, 2, 3])
print("Add row to each row:\n", arr + row)


Original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Add 10 to all elements:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Add row to each row:
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [5]:
#Normalization and Standardization
data = np.random.randint(10, 100, (5, 3))
print("Original:\n", data)

# Min-Max normalization (0–1)
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

# Z-score normalization
standardized = (data - np.mean(data)) / np.std(data)

print("Normalized:\n", normalized)
print("Standardized:\n", standardized)


Original:
 [[62 42 20]
 [16 46 59]
 [50 53 46]
 [99 35 38]
 [78 30 97]]
Normalized:
 [[0.55421687 0.31325301 0.04819277]
 [0.         0.36144578 0.51807229]
 [0.40963855 0.44578313 0.36144578]
 [1.         0.22891566 0.26506024]
 [0.74698795 0.1686747  0.97590361]]
Standardized:
 [[ 0.44477656 -0.3944245  -1.31754566]
 [-1.48538587 -0.22658429  0.3188964 ]
 [-0.05874407  0.06713608 -0.22658429]
 [ 1.99729852 -0.68814487 -0.56226471]
 [ 1.11613741 -0.89794513  1.91337841]]


In [6]:
#Solve Large Linear Systems
A = np.random.randint(1, 10, (3, 3))
b = np.array([10, 20, 30])

x = np.linalg.solve(A, b)
print("Solution x:\n", x)


Solution x:
 [-0.27888446  3.34661355  1.83266932]


In [7]:
#Boolean Indexing & Conditional Selection
arr = np.random.randint(1, 20, 10)
print("Array:", arr)

# Get elements > 10
print("Greater than 10:", arr[arr > 10])

# Replace values < 10 with 0
arr[arr < 10] = 0
print("Modified:", arr)


Array: [ 2  4  5 18  7  7 17 13 10 12]
Greater than 10: [18 17 13 12]
Modified: [ 0  0  0 18  0  0 17 13 10 12]


In [8]:
#Stacking and Splitting Arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((a, b))
h_stack = np.hstack((a, b))
split = np.hsplit(h_stack, 2)

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)
print("Split Arrays:\n", split)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Split Arrays:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [9]:
#Using np.where and Conditional Logic
arr = np.arange(1, 11)
result = np.where(arr % 2 == 0, "Even", "Odd")
print(result)


['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [10]:
# Random integers between 1 and 100 (5x5)
rand_ints = np.random.randint(1, 100, (5, 5))
print("Random Integers:\n", rand_ints)

# Normal distribution (mean=0, std=1)
normal_data = np.random.normal(0, 1, (3, 3))
print("Normal Distribution Data:\n", normal_data)


Random Integers:
 [[66 54  2 86 32]
 [80 98 18 94 46]
 [37 93 12 83 94]
 [ 7 42  5 32 56]
 [ 3 27 82 28 59]]
Normal Distribution Data:
 [[ 0.16801718 -1.04125038  1.33838052]
 [-0.60373174  0.64084886 -1.55435541]
 [ 1.12227831  1.2466386   0.31800759]]


In [11]:
#Vectorized Distance Calculation
points = np.array([[1, 2], [3, 4], [5, 6]])

# Distance matrix using broadcasting
distances = np.sqrt(((points[:, np.newaxis] - points)**2).sum(axis=2))
print("Distance Matrix:\n", distances)


Distance Matrix:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [12]:
#Block Matrices (Advanced Concatenation)
import numpy as np

A = np.ones((2, 2))
B = np.zeros((2, 2))
C = np.eye(2)
D = np.full((2, 2), 9)

block = np.block([[A, B],
                  [C, D]])

print("Block Matrix:\n", block)


Block Matrix:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 9. 9.]
 [0. 1. 9. 9.]]


In [13]:
#Fast Fourier Transform (FFT)
signal = np.array([1, 2, 1, 0, 1, 2, 1, 0])
fft_result = np.fft.fft(signal)
frequencies = np.fft.fftfreq(len(signal))

print("FFT:\n", fft_result)
print("Frequencies:\n", frequencies)


FFT:
 [8.+0.j 0.+0.j 0.-4.j 0.+0.j 0.+0.j 0.+0.j 0.+4.j 0.+0.j]
Frequencies:
 [ 0.     0.125  0.25   0.375 -0.5   -0.375 -0.25  -0.125]


In [14]:
#Correlation and Covariance Matrix
data = np.random.randn(5, 4)  # 5 samples, 4 features

cov_matrix = np.cov(data, rowvar=False)
corr_matrix = np.corrcoef(data, rowvar=False)

print("Covariance Matrix:\n", cov_matrix)
print("Correlation Matrix:\n", corr_matrix)


Covariance Matrix:
 [[ 1.26940494 -0.18567138 -0.87471031 -0.06041654]
 [-0.18567138  1.13250247  0.55557587  1.03687398]
 [-0.87471031  0.55557587  2.28372073 -0.25722283]
 [-0.06041654  1.03687398 -0.25722283  1.28880415]]
Correlation Matrix:
 [[ 1.         -0.15485502 -0.51373914 -0.04723483]
 [-0.15485502  1.          0.3454636   0.85824827]
 [-0.51373914  0.3454636   1.         -0.14993207]
 [-0.04723483  0.85824827 -0.14993207  1.        ]]


In [15]:
#Polynomial Operations
coeffs = [1, -3, 2]  # Represents x² - 3x + 2
p = np.poly1d(coeffs)

print("Polynomial:\n", p)
print("Roots:", p.roots)
print("Derivative:\n", p.deriv())
print("Value at x=5:", p(5))


Polynomial:
    2
1 x - 3 x + 2
Roots: [2. 1.]
Derivative:
  
2 x - 3
Value at x=5: 12


In [16]:
#Kronecker and Outer Products
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 5], [6, 7]])

print("Kronecker Product:\n", np.kron(a, b))
print("Outer Product:\n", np.outer([1, 2, 3], [4, 5, 6]))


Kronecker Product:
 [[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [17]:
#Advanced Masking and Index Tricks
arr = np.random.randint(-10, 10, 10)
mask = (arr > -5) & (arr < 5)
filtered = arr[mask]

print("Array:", arr)
print("Filtered (-5 < x < 5):", filtered)


Array: [-3  4 -5 -4 -7 -6  1  6  4  3]
Filtered (-5 < x < 5): [-3  4 -4  1  4  3]


In [21]:
#Singular Value Deposition (SVD)
import numpy as np

# Create a random 4x3 matrix
A = np.random.randn(4, 3)
print("Original Matrix A:\n", A)

# Perform Singular Value Decomposition
U, S, Vt = np.linalg.svd(A, full_matrices=False)

print("\nU (Left Singular Vectors):\n", U)
print("\nSingular Values (Diagonal of S):\n", S)
print("\nVᵗ (Right Singular Vectors Transposed):\n", Vt)

# Reconstruct A from U, S, Vt
A_reconstructed = U @ np.diag(S) @ Vt
print("\nReconstructed A:\n", A_reconstructed)

# Check reconstruction accuracy
print("\nReconstruction Error:", np.linalg.norm(A - A_reconstructed))


Original Matrix A:
 [[-0.77756921  0.59384101  1.64331658]
 [ 0.04359244 -2.49954086 -1.52832404]
 [-1.11092891  1.12186193 -0.84841416]
 [-0.54722951  0.5645343  -1.42293268]]

U (Left Singular Vectors):
 [[ 0.48404113  0.23416353  0.78063236]
 [-0.85541203  0.11502181  0.50456881]
 [ 0.13654632 -0.70626454  0.36769847]
 [-0.12381258 -0.65812447 -0.02865772]]

Singular Values (Diagonal of S):
 [3.3497881  2.38799368 1.08396299]

Vᵗ (Right Singular Vectors Transposed):
 [[-0.148548    0.74896393  0.64574494]
 [ 0.40523162 -0.5495454   0.7306074 ]
 [-0.90206475 -0.37020654  0.22187   ]]

Reconstructed A:
 [[-0.77756921  0.59384101  1.64331658]
 [ 0.04359244 -2.49954086 -1.52832404]
 [-1.11092891  1.12186193 -0.84841416]
 [-0.54722951  0.5645343  -1.42293268]]

Reconstruction Error: 1.800064634030038e-15


In [22]:
#Tensor Manipulations (n-D arrays)
tensor = np.random.randint(0, 10, (3, 3, 3))
print("Tensor Shape:", tensor.shape)

# Mean along each axis
print("Mean along axis 0:\n", np.mean(tensor, axis=0))
print("Mean along axis 1:\n", np.mean(tensor, axis=1))


Tensor Shape: (3, 3, 3)
Mean along axis 0:
 [[8.33333333 2.33333333 2.66666667]
 [4.33333333 5.33333333 4.        ]
 [4.66666667 3.33333333 4.33333333]]
Mean along axis 1:
 [[4.33333333 4.33333333 3.        ]
 [8.         4.         3.        ]
 [5.         2.66666667 5.        ]]


In [23]:
#Performance Optimization
import time

arr = np.random.rand(1_000_000)

# Normal Python sum
start = time.time()
sum_py = sum(arr)
print("Python sum time:", time.time() - start)

# NumPy sum
start = time.time()
sum_np = np.sum(arr)
print("NumPy sum time:", time.time() - start)


Python sum time: 0.5438210964202881
NumPy sum time: 0.0032448768615722656


In [24]:
#Distance Metrics
points = np.random.rand(5, 3)
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
dist = np.sqrt(np.sum(diff**2, axis=-1))

print("Pairwise Distance Matrix:\n", dist)


Pairwise Distance Matrix:
 [[0.         0.55342548 0.75149615 0.26680575 0.72255454]
 [0.55342548 0.         1.08752382 0.77456516 1.18596348]
 [0.75149615 1.08752382 0.         0.86861192 0.71209659]
 [0.26680575 0.77456516 0.86861192 0.         0.70873814]
 [0.72255454 1.18596348 0.71209659 0.70873814 0.        ]]


In [25]:
#Rolling / Sliding Window Calculations
def moving_average(arr, window):
    return np.convolve(arr, np.ones(window)/window, mode='valid')

data = np.array([1, 2, 3, 4, 5, 6, 7])
print("Moving Average (window=3):", moving_average(data, 3))


Moving Average (window=3): [2. 3. 4. 5. 6.]


In [26]:
#Checkerboard Pattern (Alternating Logic)
import numpy as np

n = 8
checker = np.zeros((n, n), dtype=int)
checker[::2, 1::2] = 1
checker[1::2, ::2] = 1
print(checker)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#Create Border Matrix
arr = np.zeros((6, 6), dtype=int)
arr[0, :] = arr[-1, :] = arr[:, 0] = arr[:, -1] = 1
print(arr)


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [28]:
#Replace Multiples Using Boolean Logic
arr = np.arange(1, 21)
arr[(arr % 3 == 0) & (arr % 5 == 0)] = 99
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 99 16 17 18 19 20]


In [29]:
#Nearest Value in Array
arr = np.random.randint(0, 100, 10)
target = 42
nearest = arr[np.abs(arr - target).argmin()]
print("Array:", arr)
print("Nearest to 42:", nearest)


Array: [ 5 19  3 20 43 72 53 93  8 34]
Nearest to 42: 43


In [30]:
#Find All Pairs With Given Sum
arr = np.array([1, 3, 5, 7, 9])
target = 10

sum_matrix = arr[:, None] + arr
pairs = np.argwhere(sum_matrix == target)
print("Pairs of indices:", pairs)


Pairs of indices: [[0 4]
 [1 3]
 [2 2]
 [3 1]
 [4 0]]


In [32]:
import numpy as np

n = 4
mat = np.zeros((n, n), dtype=int)
val, layer = 1, 0

while val <= n * n:
    # Top row (left → right)
    mat[layer, layer:n-layer] = np.arange(val, val + (n - 2*layer))
    val += (n - 2*layer)

    # Right column (top → bottom)
    mat[layer+1:n-layer, n-layer-1] = np.arange(val, val + (n - 2*layer - 1))
    val += (n - 2*layer - 1)

    # Bottom row (right → left)
    if layer != n - layer - 1:  # avoid overwriting center for odd n
        mat[n-layer-1, layer:n-layer-1][::-1] = np.arange(val, val + (n - 2*layer - 1))
        val += (n - 2*layer - 1)

    # Left column (bottom → top)
    if layer != n - layer - 1:
        mat[layer+1:n-layer-1, layer][::-1] = np.arange(val, val + (n - 2*layer - 2))
        val += (n - 2*layer - 2)

    layer += 1

print(mat)


[[ 1  2  3  4]
 [12 13 14  5]
 [11 16 15  6]
 [10  9  8  7]]


In [33]:
#Count Consecutive Repeats
arr = np.array([1,1,2,2,2,3,3,4,5,5])
changes = np.diff(arr) != 0
idx = np.append(np.where(changes), len(arr) - 1)
counts = np.diff(np.append(-1, idx))
values = arr[idx]
print("Values:", values)
print("Counts:", counts)


Values: [1 2 3 4 5]
Counts: [2 3 2 1 2]


In [34]:
#Local Maxima and Minima
arr = np.array([1, 3, 7, 1, 2, 6, 0, 1])
maxima = (arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])
minima = (arr[1:-1] < arr[:-2]) & (arr[1:-1] < arr[2:])
print("Local maxima indices:", np.where(maxima)[0] + 1)
print("Local minima indices:", np.where(minima)[0] + 1)


Local maxima indices: [2 5]
Local minima indices: [3 6]


In [35]:
#Unique Rows in a 2D Array
arr = np.array([[1,2,3],[1,2,3],[2,3,4],[4,5,6]])
unique = np.unique(arr, axis=0)
print(unique)


[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [36]:
#Generate a Pascal’s Triangle
n = 6
triangle = np.zeros((n, n), dtype=int)
triangle[:,0] = 1

for i in range(1, n):
    triangle[i, 1:i+1] = triangle[i-1, :i] + triangle[i-1, 1:i+1]

print(triangle)


[[ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 1  2  1  0  0  0]
 [ 1  3  3  1  0  0]
 [ 1  4  6  4  1  0]
 [ 1  5 10 10  5  1]]


In [37]:
#Sudoku Row/Column/Block Validation
sudoku = np.array([
 [5,3,4,6,7,8,9,1,2],
 [6,7,2,1,9,5,3,4,8],
 [1,9,8,3,4,2,5,6,7],
 [8,5,9,7,6,1,4,2,3],
 [4,2,6,8,5,3,7,9,1],
 [7,1,3,9,2,4,8,5,6],
 [9,6,1,5,3,7,2,8,4],
 [2,8,7,4,1,9,6,3,5],
 [3,4,5,2,8,6,1,7,9]
])

valid = all(np.all(np.sort(x) == np.arange(1, 10)) for x in 
            np.vstack((sudoku, sudoku.T, sudoku.reshape(3,3,3,3).swapaxes(1,2).reshape(-1,9))))
print("Sudoku valid:", valid)


Sudoku valid: True


In [38]:
#Logical Compression
arr = np.array([1,1,0,1,1,1,0,1,0,1,1,1,1], dtype=bool)
diff = np.diff(np.concatenate(([0], arr.view(np.int8), [0])))
starts = np.where(diff == 1)[0]
ends = np.where(diff == -1)[0]
lengths = ends - starts
longest = starts[lengths.argmax()], ends[lengths.argmax()] - 1
print("Longest True sequence:", longest)


Longest True sequence: (9, 12)


In [41]:
#Find All Unique Triplets That Sum to Zero
import numpy as np

arr = np.array([-1, 0, 1, 2, -1, -4])
arr.sort()  # Sort the array first
triplets = set()  # Use set to store unique triplets

for i in range(len(arr)-2):
    a = arr[i]
    left, right = i + 1, len(arr) - 1

    while left < right:
        total = a + arr[left] + arr[right]
        if total == 0:
            triplets.add((a, arr[left], arr[right]))
            left += 1
            right -= 1
        elif total < 0:
            left += 1
        else:
            right -= 1

# Convert set to list for printing
triplets = list(triplets)
print("Triplets that sum to 0:", triplets)



Triplets that sum to 0: [(-1, 0, 1), (-1, -1, 2)]


In [42]:
#Magic Square Validation
square = np.array([[8,1,6],[3,5,7],[4,9,2]])
s = np.sum(square, axis=0)
print("Is Magic Square:", 
      np.all(np.sum(square, axis=0) == np.sum(square, axis=1)) and 
      np.sum(np.diag(square)) == np.sum(np.fliplr(square).diagonal()))


Is Magic Square: True
