In [2]:
import numpy as np

In [29]:
z=np.array([[[1,2,9,13],
             [3,4,10,14]],
            
            [[5,6,11,15],
             [7,8,12,16]]])

In [30]:
z

array([[[ 1,  2,  9, 13],
        [ 3,  4, 10, 14]],

       [[ 5,  6, 11, 15],
        [ 7,  8, 12, 16]]])

In [31]:
z[:,:,1::2]

array([[[ 2, 13],
        [ 4, 14]],

       [[ 6, 15],
        [ 8, 16]]])

In [8]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [9]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
b=np.array([[1,2],
            [3,4]])
c=np.array([[5,6],
            [7,8]])

In [11]:
sum=b+c

In [12]:
sum

array([[ 6,  8],
       [10, 12]])

In [13]:
sub=b-c

In [14]:
sub

array([[-4, -4],
       [-4, -4]])

In [18]:
mul=b*c

In [19]:
mul

array([[ 5, 12],
       [21, 32]])

In [20]:
div=b/c

In [21]:
div

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [15]:
x=np.array([[1,2],
            [3,4],
            [5,6]])
y=np.array([[6,5,4],
            [3,2,1]])

In [16]:
x.dot(y)

array([[12,  9,  6],
       [30, 23, 16],
       [48, 37, 26]])

Tuple

In [32]:
()

()

In [33]:
a=()

In [36]:
b=tuple()

In [37]:
b

()

In [40]:
a='b','c'

In [41]:
a

('b', 'c')

In [47]:
b=tuple((2,3,4,5))
b

(2, 3, 4, 5)

In [46]:
b=(2,3,4,5)
b

(2, 3, 4, 5)

In [49]:
a=tuple([1,2,3,4])
a

(1, 2, 3, 4)

In [50]:
c=tuple('Bankai')

In [51]:
c

('B', 'a', 'n', 'k', 'a', 'i')

In [52]:
x=('MH','31','AZ','3219')
a,b,c,d=x
print(a,b,c,d)

MH 31 AZ 3219


In [53]:
t1=(1,2,3)+(4,5,6)
t1

(1, 2, 3, 4, 5, 6)

In [54]:
t1=('Nagpur','440005')
t2=('Nagpur','440005')
t1 is t2

False

In [55]:
t1==t2

True

In [56]:
hash(t1)

756614976290164255

In [57]:
hash(t2)

756614976290164255

In [58]:
hash(t1) is hash(t2)

False

In [59]:
hash(t1)==hash(t2)

True

In [60]:
x=('apple',[1,2,3],('x','y',24))

In [61]:
x[0]

'apple'

In [62]:
x[1]

[1, 2, 3]

In [66]:
x[0][1]

'p'

In [67]:
x[1][1]

2

In [68]:
t3=('B', 'a', 'n', 'k', 'a', 'i')

In [69]:
t3[-1]

'i'

In [73]:
t3[-3:-1]

('k', 'a')

In [74]:
t3[2:]

('n', 'k', 'a', 'i')

In [75]:
t3[:]

('B', 'a', 'n', 'k', 'a', 'i')

In [77]:
t4=(1,2,3,[4,5])

In [78]:
t4[1]

2

In [80]:
t4[3][0]

4

In [81]:
t4[3][1]=6

In [82]:
t4

(1, 2, 3, [4, 6])

In [83]:
str1='haki'
tup=tuple(str1)
tup

('h', 'a', 'k', 'i')

In [86]:
rt1=tup[::-1]
rt1

('i', 'k', 'a', 'h')

In [89]:
rt2=reversed(tup)
print(rt2)

In [92]:
rt3=()
for i in reversed(range(len(tup))):
    rt3+=(tup[i],)
print(rt3)

('i', 'k', 'a', 'h')


In [94]:
rt4=()
for i in range(len(tup)-1,-1,-1):
    rt4+=(tup[i],)
print(rt4)

('i', 'k', 'a', 'h')


In [95]:
from collections import namedtuple
vehicle=namedtuple('type','state city series no')
car=vehicle(state='MH',city='31',series='DK',no='1730')
print(car)

type(state='MH', city='31', series='DK', no='1730')


In [96]:
print(car.state,car.city,car.series,car.no)

MH 31 DK 1730


In [101]:
#remove space between elements of string tuple and save as string
t=(12,34,'acs','a c s',23)
print("Original tuple is")
print(t)
st=str(t).replace(' ','')
print("Tuple after removing spaces is")
print(str(st))

Original tuple is
(12, 34, 'acs', 'a c s', 23)
Tuple after removing spaces is
(12,34,'acs','acs',23)


In [107]:
#printing list of tuple in table format(method1)
list1=[('Naruto','Leaf',92.34),
       ('Luffy','East Blue',85.85),
       ('Ichigo','Karakura Town',82.12)]
print("Name\t\tCity\t\tScore")
for a in range(40):
    print('-',end='')
print()
for ele1,ele2,ele3 in list1:
    print("{:16}{:16}{}".format(ele1,ele2,ele3))

Name		City		Score
----------------------------------------
Naruto          Leaf            92.34
Luffy           East Blue       85.85
Ichigo          Karakura Town   82.12


In [113]:
#printing list of tuple in table format(method2)
list2=[('Naruto','Leaf',92.34),
       ('Luffy','East Blue',85.85),
       ('Ichigo','Karakura Town',82.12)]
column_width=16
print("Name\t\tCity\t\tScore")
for a in range(40):
    print('-',end='')
print()
for tup in list2:
    for ele in tup:
        print(str(ele).ljust(column_width),end='')
    print()

Name		City		Score
----------------------------------------
Naruto          Leaf            92.34           
Luffy           East Blue       85.85           
Ichigo          Karakura Town   82.12           


In [116]:
#check if any list element exist in tuple
tup=(51,35,12,45,73)
print("The tuple elements are "+str(tup))
lst=[12,0,4,35,23]
print("The list elements are"+str(lst))
status=False
for ele in lst:
    if ele in tup:
        status=True
        break
print("If any element in list exist in tuple? \n"+str(status))

The tuple elements are (51, 35, 12, 45, 73)
The list elements are[12, 0, 4, 35, 23]
If any element in list exist in tuple? 
True


In [125]:
#convert tuple to string (method1)
tup=('B', 'a', 'n', 'k', 'a', 'i')
print("Tuple items are",tup)
str1=''.join(tup)
print("String from tuple is",str1)

Tuple items are ('B', 'a', 'n', 'k', 'a', 'i')
String from tuple is Bankai


In [126]:
#convert tuple to string (method2)
tup=('B', 'a', 'n', 'k', 'a', 'i')
print("Tuple items are",tup)
str2=''
for t in tup:
    str2=str2+t
print("String from tuple is",str2)

Tuple items are ('B', 'a', 'n', 'k', 'a', 'i')
String from tuple is Bankai


In [128]:
#convert tuple to string (method3)
tup=('B', 'a', 'n', 'k', 'a', 'i')
print("Tuple items are",tup)
str3=''
for i in range(len(tup)):
    str3=str3+tup[i]
print("String from tuple is",str3)

Tuple items are ('B', 'a', 'n', 'k', 'a', 'i')
String from tuple is Bankai
